name: Pipeline de Produção

env:
    NODE_ENV: production
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main

jobs:
    job1:
        name: CI, build e criação de artefatos
        runs-on: ubuntu-latest
        steps:
            - name: Pegar código do Repositório
              uses: actions/checkout@v3

            - name: Instalando pacotes do npm
              run: npm install

            - name: Gerar documentação Swagger.json
              run: npm run autoDoc
            
            - name: Apagando pasta node_modules
              run: rm -rf node_modules

            - name: Apagando pasta .git
              run: rm -rf .git

            - name: Arquivo e pastas
              run: ls

            - name: Criar artefato ZIP
              uses: actions/upload-artifact@v3
              with:
                  name: artefato
                  retention-days: 1
                  path: ./

    job2:
        name: Deploy na vercel
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: Baixando artefato do código buildado
              uses: actions/download-artifact@v3
              with:
                  name: artefato

            - name: Instalando pacotes do npm
              run: npm install
            
            - name: Arquivo e pastas do artefato
              run: ls

            - name: Instalando CLI da Vercel
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
