name: Pipeline de Deploy

env:
    NODE_ENV: production
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: 
            - main

jobs:
    job1:
        name: CI - Build e criação do artefato
        runs-on: ubuntu-latest

        steps:
        - name: Pegar o código do repositório
          uses: actions/checkout@v4

        - name: Configurando Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 18

        - name: Instalando os pacotes do npm
          run: npm install

        - name: Gerando documentação swagger.json
          run: npm run autoDoc

        - name: Apagando pasta node_modules
          run: rm -rf node_modules

        - name: Apagando pasta .git
          run: rm -rf .git

        - name: Listando arquivos e pastas
          run: ls

        - name: Criando artefato ZIP do código
          uses: actions/upload-artifact@v4
          with:
              name: artefato
              retention-days: 1
              path: ./

    job2:
        name: CD - Deploy na Vercel
        needs: job1
        runs-on: ubuntu-latest

        steps:
        - name: Baixando Artefato do código
          uses: actions/download-artifact@v4
          with:
              name: artefato

        - name: Instalando os pacotes do npm
          run: npm install

        - name: Listando arquivos e pastas do artefato
          run: ls

        - name: Instalando CLI da Vercel
          run: npm install --global vercel@latest

        - name: Buscando informações de ambiente no Vercel
          run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

        - name: Building do artefato do projeto
          run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

        - name: Deploy do artefato do projeto na Vercel
          run: vercel deploy --prebuild --prod --token=${{ secrets.VERCEL_TOKEN }}
